version: "3.8"
services: 
    api:
        build:
            context: ./api
        volumes:
            - ./api:/usr/src/app
            - /usr/src/app/node_modules
        ports: 
            - 5000:5000
            - 5001:5001 
        environment: 
            PORT: 5000
            NODE_ENV: development
            DATBASE_USER: test
            DATABASE_NAME: codeboxtv
            DATABASE_PASSWORD: test
            DATABASE_HOST: postgres
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: codeboxtv
            POSTGRES_HOST_AUTH_METHOD: trust
volumes:
    postgres-data: